### ISSUE TITLE
Ace Of Spaces texture issue

### ISSUE THREAD

**Issue by JamesTheMaker** [Mr-Pineapple/AdditionalGuns#1]
The back of the Ace of Spades' cylinder has a glitchy texture.
![2021-07-07_08 48 38](https://user-images.githubusercontent.com/79481373/124761907-48d75e00-df00-11eb-88e7-a8a661d865d3.png)

**Comment by Mr-Pineapple** [comment]
Are you using any other mods with this, I don't get this issue on my game

**Comment by JamesTheMaker** [comment]
I have a handful more, but none affect rendering except Sodium Reforged. And, even with it uninstalled, the bug still occurs.

**Comment by Autovw** [comment]
Can someone do me a favor and verify if this issue still occurs on the latest version?

**Comment by Autovw** [comment]
Well, I can't replicate this issue on my end and I haven't heard from anyone else about this either.
I'll close it for now, but I can always reopen it later if this still seem to occur.
