### ISSUE TITLE
Z-Fighting, scope smol scope in SSG and i forgor 💀 to add tint for m4a4 aiming bar and also something strange with m4a4

### ISSUE THREAD

**Issue by XviktorwoodX** [Mr-Pineapple/AdditionalGuns#14]
![2021-11-06_13 33 59](https://user-images.githubusercontent.com/93402694/140610649-00607836-b427-41c3-8d0a-ee8a9e380038.png)
![2021-11-06_13 34 29](https://user-images.githubusercontent.com/93402694/140610654-a9a2af43-8954-4493-9a50-a85e2b2eccb5.png)
![2021-11-06_14 06 37](https://user-images.githubusercontent.com/93402694/140610681-75a308c7-62c1-454c-9aac-3a8e3b7e9707.png)

**Comment by Autovw** [comment]
I've assigned you to this issue so you can fix it with a PR. (we talked about it on Discord earlier today)
I'll fix the scope issue once you've finished your PR. :)

**Comment by Autovw** [comment]
Everything should be fixed in the next update.
