### ISSUE TITLE
m4a4 missing color, raven claw looking small

### ISSUE THREAD

**Issue by MeCrafX** [Mr-Pineapple/AdditionalGuns#18]
Hello I found some issues

m4a4 is missing colorable part
![image](https://user-images.githubusercontent.com/93524313/144233376-bcec1082-4308-4b7e-b570-b79a9369bc08.png)

raven claw is looking very small and hands position is weird
![image](https://user-images.githubusercontent.com/93524313/144233482-2f65d489-e90a-4da2-9e4e-a2e25bea7c07.png)

can you maybe fix this?

**Comment by XviktorwoodX** [comment]
m4a4 already fixed, and you can see fix in next update

**Comment by Autovw** [comment]
Thanks for your report, the issues should be fixed in the next update.
