### ISSUE TITLE
suggestions and questions for mod

### ISSUE THREAD

**Issue by MeCrafX** [Mr-Pineapple/AdditionalGuns#19]
Hello I have some suggestions and questions

Suggestions
add more sounds, most sounds don't fit with gun
some guns are OP, maybe make more balance
add images to cursefroge maybe

Questions
I was wondering if you plan updating to newer version or stay on 1.16?
when will mod go out beta?

thanks in avance

**Comment by Autovw** [comment]
This is a community mod and it relies on content created and contributed by the community. I think @Voider404 was working on some custom sounds if I remember correctly? 
As for balancing the gun stats: we're up for discussion. Please let us know your thoughts.
I'll work on improving the CurseForge page whenever I've got the time to do so.

Are we going to update past 1.16? Yes. Definitely. But we'll have to wait until MrCrayfish updates the Gun Mod first.
Full release when? The answer to that would be: Whenever we feel like the mod is 'stable' enough (from a technical perspective) basically.
