### ISSUE TITLE
Reference map does not generate

### ISSUE THREAD

**Issue by wonklabs** [Mr-Pineapple/AdditionalGuns#23]
Help I'm getting an error when I try to startup my server
![image](https://user-images.githubusercontent.com/96693295/147413032-4bf112ab-81ed-43b9-8dd6-0ded4674cc32.png)

I'm using a server so not a "development environment" meaning I can't ignore it?
Everything still works fine but I don't really know what to do

Server:
- Minecraft: 1.16.5
- Forge: 36.2.22
- Host: my own pc
- Memory: 2048MB
- Player limit: 10
- Total mods installed: 13

Mod:
- Version: 0.4.2-1.16.5

**Comment by Autovw** [comment]
It's just a warning, I'll see if I can fix it in the next update.
