### ISSUE TITLE
Reloading error in server game

### ISSUE THREAD

**Issue by ParasideEx** [Mr-Pineapple/AdditionalGuns#24]
Hi! I found a strange bug when I used the MrCrayfish's Gun Mod and the Additional Guns Mod in my 1.16.5 server😫 . After the player dies and resurrects in the game, he cannot reload ammunition. After pressing the reload button, the reload animation can appear, but there is no sound of reload, and in fact, the gun was not successfully reloaded. Players must exit the server and re-enter to return to normal. Is there any way to solve this problem completely?

MrCrayfish's Gun Mod  MrCrayfish's Gun Mod:1.1.0-1.16.5
Additional Guns Mod Version: 0.4.2-1.16.5

Minecraft: 1.16.5
Forge: 36.2.22
Memory: 10GB

**Comment by Autovw** [comment]
This issue is not caused by Additional Guns. Even though I am not able to replicate this issue I can tell you it's most likely caused by MrCrayfish's Gun Mod because we use their system.
