### ISSUE TITLE
Scopes not centered correctly

### ISSUE THREAD

**Issue by JamesTheMaker** [Mr-Pineapple/AdditionalGuns#3]
The 9A-91 Sight isn't centered when aiming down it. Could fix by raising model height in some way?
![2021-07-07_08 54 04](https://user-images.githubusercontent.com/79481373/124762545-019d9d00-df01-11eb-9c13-e5acf3dabdd7.png)

**Comment by Autovw** [comment]
This issue _should_ be fixed in the next update. :)

**Comment by Autovw** [comment]
I've made an attempt at fixing the positions, feel free to re-open this issue if the positions are still not "good enough"

**Comment by Mercuriousity** [comment]
The Kobra Sight have a slightly wrong position when attached on any guns.
![image](https://user-images.githubusercontent.com/102347222/160333038-f4839460-f937-4c4a-b296-4e61ee66da9b.png)
