### ISSUE TITLE
better direction for mod

### ISSUE THREAD

**Issue by IndustrialSpecials** [Mr-Pineapple/AdditionalGuns#32]
I understand this is currently just a simple add-on for MrCrayfish's Gun Mod, but it would be better to finally make this mod independent. The concept of add-ons isn't generally liked by the users. This would be a great opportunity to finally ditch Forge, because no one wants to use such an outdated and slow modloader. Come on, it's 2022 already. Not 2015. I agree Fabric isn't the best of the best, but it would make moving to Quilt a lot easier in the future. (Quilt looks promising and will eventually take over anyway)

It's better to make the decision now, they'll make it only harder for devs in the future and I'm sure a team of 2 devs can sort this out without any major issues considering some random youtuber wrote the base mod in the first place. Look at Timeless and Classic, they also became independent, but they should've ditched Forge in the process.

**Comment by Stabilizer360** [comment]
Wait really

**Comment by Stabilizer360** [comment]
Yeah you are right they need to update the mod and pay attention add sounds for every Gun and adjust the guns position just like MrCrayfish guns and fix some bugs in Pistols in your mod my character Arm was glitching inside the MP7A1 and pistol Schwarlose and lot others 
I hope you read this and Fix this issue Real quick.

**Comment by Autovw** [comment]
@IndustrialSpecials This is an add-on for MrCrayfish's Gun Mod and we have no plans changing that. The issue tracker is not the right place for this kind of discussion.

@Stabilizer360 Please [create a new issue](https://github.com/Mr-Pineapple/AdditionalGuns/issues/new) and provide some screenshots of the issue(s).
