### ISSUE TITLE
Not able to use perks

### ISSUE THREAD

**Issue by FredB-mine** [Mr-Pineapple/AdditionalGuns#34]
I pressed 'Z' for a long while.However,It doesn;t work at all! Why is that happening?

**Comment by FredB-mine** [comment]
And I cannot load bullets now

**Comment by Autovw** [comment]
Press 'Z' while in-game (not in the inventory)
If that still doesn't work there might be a keybind conflict. Please use the ``#additional-guns`` channel on [Discord](https://discord.gg/mNWSEB5) if you need more help :)
