### ISSUE TITLE
Raven's Claw texture causes mipmaps not to generate

### ISSUE THREAD

**Issue by Stanicek3** [Mr-Pineapple/AdditionalGuns#36]
Due to the texture of the Raven's Claw being odd (as in not even), it causes mipmaps to not generate with the launch of the game.

Line from latest.log: "Texture additionalguns:item/ravens_claw_decal with size 240x63 limits mip level from 4 to 0"

Edit: Sorry, I typed this when I first woke up in the morning. Changed “uneven” to “not even”

**Comment by Stanicek3** [comment]
1.16.5 - Forge v36.2.34

**Comment by Autovw** [comment]
Thanks for the issue report, issue will be fixed in the very next update.
