### ISSUE TITLE
M4A4 seems tilted upwards when aiming.

### ISSUE THREAD

**Issue by Igggosha** [Mr-Pineapple/AdditionalGuns#44]
<img width="569" alt="Знімок екрана 2022-07-02 о 23 28 06" src="https://user-images.githubusercontent.com/108592631/177015317-d1ad22a7-79b4-478c-bfda-b71b575912aa.png">
Gun is supposed to be faced more straight for the iron dights to align.

**Comment by CasualNoLifer** [comment]
This has been fixed and the updated version will appear in the next update. :)
