### ISSUE TITLE
Mod fails to load

### ISSUE THREAD

**Issue by august54742** [Mr-Pineapple/AdditionalGuns#50]
<img width="649" alt="error2" src="https://user-images.githubusercontent.com/109191670/178844738-6382f1b0-0047-44aa-b6f5-86ac11f465e2.png">
The mod fails to load with error java.lang.reflect.InvocationTargetException: null, the base mod and framework is fine.
I am running forge version 41.0.98 if that helps

**Comment by Autovw** [comment]
This is a known issue and it will be fixed in the very next update. Unfortunately we are in the middle of development right now, but we'll try our best to get the update out as soon as possible.

**Comment by Autovw** [comment]
Issue is fixed in Additional Guns 0.7.0, update to receive the fix :)
