### ISSUE TITLE
There's unofficial port version of 1.20.1

### ISSUE THREAD

**Issue by Andrew4521** [Mr-Pineapple/AdditionalGuns#98]
Could I ask of updating this mod into 1.20.1? I'll provide you the unofficial ported version of CGM 1.20.1

https://drive.google.com/file/d/1I5dbN23-d9EFnmthyCgrF8WDQ5XNio6n/view?usp=sharing

I hope the positive reaction. Have a good day

**Comment by poly-1810** [comment]
..generally, addon mods do not update to unofficial versions of a mod, unless the mod gets abandoned, which CGM has not been abandoned

**Comment by CasualNoLifer** [comment]
> Could I ask of updating this mod into 1.20.1? I'll provide you the unofficial ported version of CGM 1.20.1
> 
> https://drive.google.com/file/d/1I5dbN23-d9EFnmthyCgrF8WDQ5XNio6n/view?usp=sharing
> 
> I hope the positive reaction. Have a good day

This mod will not be updated to 1.20.1 until there is an official release of Crayfish's Gun Mod.
